In [23]:
import numpy as np 
import pandas as pd 

In [24]:
from sklearn.linear_model import LinearRegression

In [25]:
df=pd.read_csv("https://raw.githubusercontent.com/NeilPandey/Test_Dataset/master/house_price.csv")

In [26]:
df.head(10)

Unnamed: 0      Location  BHK  Furnishing  Sq.ft  Old(years)  Floor  Price
0          37    Whitefield    3           1   3000           1      3  28000
1          43  Bommanahalli    3           1   1650          10      0  18000
2          12    Whitefield    2           0   1000           5      3  16400
3           8    Whitefield    3           0   1600           1      9  27000
4           9    Whitefield    2           1   1200           5      1  20000
5          11    Whitefield    3           1   1760           5      8  39500
6           5    Whitefield    3           1   1870          10      3  35000
7          15    Whitefield    3           0   2200           1     10  42000
8           0    Whitefield    3           0   2100           1      7  28000
9          16    Whitefield    3           0   1704           5     13  35000

In [27]:
df.shape

(1000, 8)

In [28]:
df.isna().sum()

Unnamed: 0    0
Location      0
BHK           0
Furnishing    0
Sq.ft         0
Old(years)    0
Floor         0
Price         0
dtype: int64

In [29]:
df.dtypes

Unnamed: 0     int64
Location      object
BHK            int64
Furnishing     int64
Sq.ft          int64
Old(years)     int64
Floor          int64
Price          int64
dtype: object

In [30]:
df.max()

Unnamed: 0            49
Location      Whitefield
BHK                    3
Furnishing             1
Sq.ft               3155
Old(years)            10
Floor                 13
Price              45000
dtype: object

In [31]:
df.min()

Unnamed: 0               0
Location      Bommanahalli
BHK                      2
Furnishing               0
Sq.ft                  767
Old(years)               1
Floor                    0
Price                11000
dtype: object

In [32]:
df=df.iloc[:,1:]
##df=df.drop(['Unnamed: 0'],axis=1)

In [33]:
df

Location  BHK  Furnishing  Sq.ft  Old(years)  Floor  Price
0      Whitefield    3           1   3000           1      3  28000
1    Bommanahalli    3           1   1650          10      0  18000
2      Whitefield    2           0   1000           5      3  16400
3      Whitefield    3           0   1600           1      9  27000
4      Whitefield    2           1   1200           5      1  20000
..            ...  ...         ...    ...         ...    ...    ...
995  Bommanahalli    3           1   1460           1      2  25000
996    Whitefield    3           0   2100           1      7  28000
997  Bommanahalli    2           0   1033           5      0  16500
998  Bommanahalli    3           0   1500          10      1  22000
999    Whitefield    3           1   1768           5     11  30000

[1000 rows x 7 columns]

In [34]:
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score

In [35]:
label_enc =LabelEncoder()

In [36]:
df['Location']= label_enc.fit_transform(df['Location'])

In [37]:
df.head(10)

Location  BHK  Furnishing  Sq.ft  Old(years)  Floor  Price
0         1    3           1   3000           1      3  28000
1         0    3           1   1650          10      0  18000
2         1    2           0   1000           5      3  16400
3         1    3           0   1600           1      9  27000
4         1    2           1   1200           5      1  20000
5         1    3           1   1760           5      8  39500
6         1    3           1   1870          10      3  35000
7         1    3           0   2200           1     10  42000
8         1    3           0   2100           1      7  28000
9         1    3           0   1704           5     13  35000

In [51]:
x=df.drop('Price',axis=1)

In [52]:
y=df['Price']

In [53]:
y

0      28000
1      18000
2      16400
3      27000
4      20000
       ...  
995    25000
996    28000
997    16500
998    22000
999    30000
Name: Price, Length: 1000, dtype: int64

In [54]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state = 1)

In [55]:
x_test

Location  BHK  Furnishing  Sq.ft  Old(years)  Floor
507         1    3           0   2180           1     11
818         1    3           0   2180           1     11
452         1    3           1   1760           5      8
368         1    3           0   3155           1      1
242         1    3           0   2200           1     10
..        ...  ...         ...    ...         ...    ...
430         0    2           0    950           5      1
874         0    2           0   1400           5      2
550         0    2           1    767           1      3
608         0    3           0   1500          10      1
207         1    2           0   1000           1      3

[200 rows x 6 columns]

In [56]:
reg=LinearRegression()

In [57]:
reg.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [58]:
reg.coef_

array([4170.52671077, 2420.87088434,  978.02191931,    8.67415921,
        -55.10309957,  521.09879069])

In [59]:
reg.fit_intercept

True

In [60]:
reg.intercept_

416.4939047086373

In [61]:
y_pred=reg.predict(x_test)

In [63]:
reg.predict([[1,3,1,3000,1,3]])

array([40358.32609513])

In [64]:
reg.predict([[1,3,1,1870,10,3]])

array([30060.59828988])